# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  host: 127.0.0.1
  encoding: utf8
  reconnect: false
  database: saft7_dev
  pool: 5
  username: dbu
  password: "1234"

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: mysql2
  host: 127.0.0.1
  encoding: utf8
  reconnect: false
  database: saft7
  pool: 5
  username: dbu
  password: "1234"
